version: '3.8'
services:
  app-spring:
    image: openjdk:17
    working_dir: /app
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    volumes:
      - ./build/libs:/app
    command:
      - java
      - -jar
      - /app/TheOne-0.0.1-SNAPSHOT.jar

  mysqldb:
    platform: linux/x86_64
    image: mysql:8
    restart: "no"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: THEONE
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql






